# netlify.toml

[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/build"

[build.environment]
  CI = "false"  # prevent CRA from failing build on ESLint warnings

# Proxy API requests to Render so cookies are first-party
[[redirects]]
  from = "/api/*"
  to = "https://entropy-backend.onrender.com/api/:splat"
  status = 200
  force = true
