# netlify.toml

[build]
  base = "frontend"         # run from /frontend
  command = "npm run build" # CRA build
  publish = "build"         # <-- IMPORTANT: not frontend/build

[build.environment]
  CI = "false"              # let CRA ignore ESLint warnings

# Proxy API to Render so cookies are first-party
[[redirects]]
  from = "/api/*"
  to = "https://entropy-backend.onrender.com/api/:splat"
  status = 200
  force = true
