# netlify.toml
[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/build"

[[redirects]]
  from = "/api/*"
  to = "https://entropy-backend.onrender.com/api/:splat"
  status = 200
  force = true
